---
title: "Lab session 4 Answers"
author: "Oliver Herdson"
date: "17/10/2022"
output: html_document
---

# [Solutions for Stats Lab 4 (Week 12): SPOILER ALERT]{style="color: rgb(61, 180, 140);"} {-}
## [Exercise 1]{style="color: rgb(180, 60, 140);"}

```{r eval=FALSE}
library(ggpubr)
data(mtcars)

mtcars$cyl <- as.factor(mtcars$cyl)
mtcars$am <- as.factor(mtcars$am)

ggboxplot(mtcars, x = "cyl", y = "disp")

```
   
## [Exercise 2]{style="color: rgb(180, 60, 140);"}
```{r eval=FALSE}
ggboxplot(mtcars, x = "cyl", y = "mpg", fill = "am")
```
   
## [Exercise 3]{style="color: rgb(180, 60, 140);"}

```{r eval=FALSE}
ggbarplot(mtcars, x = "am", y = "mpg", fill = "cyl", position = position_dodge(1), add = "mean_sd")
```
    
## [Exercise 4]{style="color: rgb(180, 60, 140);"}
```{r eval=FALSE}
ggbarplot(mtcars, x = "cyl", y = "mpg", color = "cyl", position = position_dodge(1), add = "mean")
```
    
### [Exercise 5]{style="color: rgb(180, 60, 140);"}
```{r eval=FALSE}
ggbarplot(mtcars, x = "cyl", y = "wt", fill = "am", position = position_dodge(0.5), add = "mean_sd")
```

